---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/src/e2e_test/protocol_loadtest/protocol_loadtest_server_image
    context: .
    bazel:
      target: //src/e2e_test/protocol_loadtest:protocol_loadtest_server_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - src/e2e_test/protocol_loadtest/k8s/server
