---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: gke-metrics-monitoring
  namespace: plc-staging
spec:
  selector:
    matchLabels:
      app: pl-cloud
      monitoring.gke.io/scrape: 'true'
  podMetricsEndpoints:
  - port: metrics-http
    path: /metrics
    scheme: http
