---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We cannot specify a namespace here because the elastic operator and
# it's other components need to run in it's own namespace.
commonLabels:
  app: pl-cloud
resources:
- ../base/elastic/operator
- elastic
- kibana
- nats
- stan
patches:
- path: node_selector_patch.yaml
  target:
    kind: StatefulSet
